# The directory containing the pdfs to convert
pdf_dir: /home/dave_sava/AdaParse/pdf_tmp_storage

# The output directory of the workflow
out_dir: /home/dave_sava/AdaParse/test_output/nougat

# The number of PDFs to parse in each parsl task
chunk_size: 1

parser_settings:
  device: cpu
  num_data_workers: 0
  name: "nougat"
  # Recommended batch size of pages (not pdfs) is 10
  batchsize: 2
  # Path to download the checkpoint to. if already exists, will use existing.
  checkpoint: /home/dave_sava/AdaParse/checkpoints/nougat-checkpoint
  # Set mmd_out to null if you don't want to write mmd files as a byproduct.
  mmd_out: null
  # If set to false, a will skip the pdfs that already have a parsed mmd file in mmd_out
  recompute: false
  # Set to true if you want to use fp32 instead of bfloat16 (false is recommended)
  full_precision: false
  # If set to true, output text will be formatted as a markdown file.
  markdown: true
  # Preempt processing a paper if mode collapse causes repetitions (true is recommended)
  skipping: false
  # Path for the nougat-specific logs for the run.
  nougat_logs_path: /home/dave_sava/AdaParse/logs/nougat_logs

# The compute settings for the workflow
compute_settings:
  # The name of the compute platform to use
  name: local
  # The number of compute nodes to use
  num_nodes: 1
  # Make sure to update the path to your conda environment and HF cache
  worker_init: "conda activate adaparse"

